# Generated by Django 5.1 on 2024-08-15 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('estimated_time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('operator', 'Operator'), ('financial_manager', 'Financial Manager'), ('admin', 'Administrator')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('fuel_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_amount', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('station_name', models.CharField(max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('rating', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.user')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.user'),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.user')),
            ],
        ),
    ]
